// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTCtsUKaDY64u3xcyBQuYFvAHI7-kzWyY',
    appId: '1:224015796797:web:a8918ecc73565da3cd7854',
    messagingSenderId: '224015796797',
    projectId: 'habittracker-f57f4',
    authDomain: 'habittracker-f57f4.firebaseapp.com',
    databaseURL: 'https://habittracker-f57f4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'habittracker-f57f4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADbE82fQinuPjwZ225uKebY9bVlu4TsSk',
    appId: '1:224015796797:android:28c37018d097ef68cd7854',
    messagingSenderId: '224015796797',
    projectId: 'habittracker-f57f4',
    databaseURL: 'https://habittracker-f57f4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'habittracker-f57f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJmH0DEHzHDamD5rlw3_ZiXPidqZSTcKU',
    appId: '1:224015796797:ios:e1123d2f70dec88dcd7854',
    messagingSenderId: '224015796797',
    projectId: 'habittracker-f57f4',
    databaseURL: 'https://habittracker-f57f4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'habittracker-f57f4.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJmH0DEHzHDamD5rlw3_ZiXPidqZSTcKU',
    appId: '1:224015796797:ios:e1123d2f70dec88dcd7854',
    messagingSenderId: '224015796797',
    projectId: 'habittracker-f57f4',
    databaseURL: 'https://habittracker-f57f4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'habittracker-f57f4.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTCtsUKaDY64u3xcyBQuYFvAHI7-kzWyY',
    appId: '1:224015796797:web:6032aa58b59b3491cd7854',
    messagingSenderId: '224015796797',
    projectId: 'habittracker-f57f4',
    authDomain: 'habittracker-f57f4.firebaseapp.com',
    databaseURL: 'https://habittracker-f57f4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'habittracker-f57f4.firebasestorage.app',
  );
}
